databases:
- database_name: pinot
  extra: "{\r\n    \"metadata_params\": {},\r\n    \"engine_params\": {},\r\n    \"\
    metadata_cache_timeout\": {},\r\n    \"schemas_allowed_for_csv_upload\": []\r\n\
    }"
  sqlalchemy_uri: pinot+http://pinot:8000/query?server=http%3A%2F%2Fpinot%3A9000%2F
  tables:
  - columns:
    - column_name: <new column>
      expression: DATETIMECONVERT(epoch_timestamp, '1:MILLISECONDS:EPOCH', '1:MILLISECONDS:EPOCH',
        '30:DAYS')
      is_dttm: true
      python_date_format: epoch_ms
      verbose_name: published_day
    - column_name: epoch_timestamp
      is_dttm: true
      python_date_format: epoch_ms
      type: LONG
    - column_name: new_june_2018
      type: LONG
    - column_name: tco1_step1
      type: STRING
    - column_name: tco2_step1
      type: STRING
    - column_name: tco3_step1
      type: STRING
    - column_name: external_author_id
      type: STRING
    - column_name: alt_external_id
      type: STRING
    - column_name: account_category
      type: STRING
    - column_name: harvested_date
      type: STRING
    - column_name: publish_date
      type: STRING
    - column_name: account_type
      type: STRING
    - column_name: article_url
      type: STRING
    - column_name: tweet_id
      type: STRING
    - column_name: post_type
      type: STRING
    - column_name: language
      type: STRING
    - column_name: author
      type: STRING
    - column_name: content
      type: STRING
    - column_name: region
      type: STRING
    - column_name: updates
      type: LONG
    - column_name: retweet
      type: LONG
    - column_name: followers
      type: LONG
    - column_name: following
      type: LONG
    metrics:
    - expression: COUNT(*)
      metric_name: count
      verbose_name: COUNT(*)
    params: '{"remote_id": 1, "database_name": "pinot", "import_time": 1600905429}'
    table_name: russianTrollTweets
  - columns:
    - column_name: epoch_timestamp
      is_dttm: true
      python_date_format: epoch_ms
      type: LONG
    - column_name: new_june_2018
      type: LONG
    - column_name: tco1_step1
      type: STRING
    - column_name: tco2_step1
      type: STRING
    - column_name: tco3_step1
      type: STRING
    - column_name: external_author_id
      type: STRING
    - column_name: alt_external_id
      type: STRING
    - column_name: account_category
      type: STRING
    - column_name: harvested_date
      type: STRING
    - column_name: publish_date
      type: STRING
    - column_name: account_type
      type: STRING
    - column_name: entity_category
      type: STRING
    - column_name: article_url
      type: STRING
    - column_name: entity_name
      type: STRING
    - column_name: tweet_id
      type: STRING
    - column_name: post_type
      type: STRING
    - column_name: language
      type: STRING
    - column_name: author
      type: STRING
    - column_name: content
      type: STRING
    - column_name: region
      type: STRING
    - column_name: updates
      type: LONG
    - column_name: retweet
      type: LONG
    - column_name: followers
      type: LONG
    - column_name: following
      type: LONG
    metrics:
    - expression: COUNT(*)
      metric_name: count
      verbose_name: COUNT(*)
    table_name: tweetTextEntities
